<?php

namespace pixelwerft\useraudit\migrations;

use craft\db\Migration;

/**
 * v2.3.0 — Adds `sessionId` (VARCHAR 36, nullable) to
 * {{%user_activity_log}} for the session-lifecycle feature.
 *
 * A session id is a UUID string generated by the AFTER_LOGIN hook and
 * stashed in the Craft session under `userAudit.sessionId`. Every
 * subsequent audit row written for the same browser session carries
 * it, letting the BEFORE_LOGOUT hook resolve the matching login row
 * and compute the session duration. `session_expired` events do NOT
 * carry a session id — they are client-detected on the PWA and there
 * is no way to correlate them back to a server-issued id without
 * client cooperation.
 *
 * Idempotent: schema check + column check. Safe to re-run.
 */
class m260806_120000_add_session_id_column extends Migration
{
    private const TABLE = '{{%user_activity_log}}';

    public function safeUp(): bool
    {
        $schema = $this->db->getTableSchema(self::TABLE);
        if ($schema === null) {
            // Fresh installs get sessionId directly from Install.php.
            return true;
        }

        if ($schema->getColumn('sessionId') === null) {
            $this->addColumn(self::TABLE, 'sessionId', $this->string(36)->after('client'));
            $this->createIndex(null, self::TABLE, 'sessionId');
        }

        return true;
    }

    public function safeDown(): bool
    {
        $schema = $this->db->getTableSchema(self::TABLE);
        if ($schema !== null && $schema->getColumn('sessionId') !== null) {
            $this->dropColumn(self::TABLE, 'sessionId');
        }
        return true;
    }
}
